name:                passman
version:             0.3.1
license:             LGPL-3.0-or-later
author:              "Jonathan Lamothe"
maintainer:          "jonathan@jlamothe.net"
copyright:           "(C) 2018-2021 Jonathan Lamothe"
homepage:            https://codeberg.org/jlamothe/passman

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            a simple password manager
category:            Security

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlamothe/passman#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.5.6.0 && < 1.6
- bytestring >= 0.10.12.0 && < 0.11
- containers >= 0.6.2.1 && < 0.7
- microlens >= 0.4.11.2 && < 0.5
- microlens-th >= 0.4.3.6 && < 0.5
- random >=1.1 && < 1.2

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
  - base16-bytestring >= 0.1.1.7 && < 0.2
  - base64-bytestring >= 1.1.0.0 && < 1.2
  - SHA >= 1.6.4.4 && < 1.7
  - text >= 1.2.4.1 && < 1.3

executables:
  passman:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - passman
    - easy-file >= 0.2.2 && < 0.3
    - HCL >= 1.8 && < 1.9
    - transformers >= 0.5.6.2 && < 0.6

tests:
  passman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - passman
    - HUnit
