name:                passman
version:             0.0
github:              "jlamothe/passman"
license:             LGPL-3
author:              "Jonathan Lamothe"
maintainer:          "jlamothe1980@gmail.com"
copyright:           "(C) 2018 Jonathan Lamothe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            a simple password manager
category:            Security

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlamothe/passman#readme>

dependencies:
- base >= 4.7 && < 5
- lens

library:
  source-dirs: src

executables:
  passman:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - passman
    - HCL >= 1.7.1 && < 2
    - transformers

tests:
  passman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - passman
    - HUnit
